INSERT INTO subgenres
    (id, subgenre_name, origin_id, inspiration_id, inspiration_name)
VALUES
    (1, 'speed metal', 4, 1, 'classical' ),
    (2, 'power metal', 4, 1, 'classical', 1, 'speed metal' ),
    (3, 'pop metal', 9, 'pop', 4 ),
    (4, 'hair metal', 6, 'rock', 4 ),
    (5, 'neoclassical metal', 4, 1, 'classical' ),
    (6, 'symphonic metal', 4, 1, 'classical' ),
    (7, 'prog metal', 1, 'jazz', 4 ),
    (8, 'thrash metal', 8, 'punk', 4 ),
    (9, 'black metal', 4, 8, 'thrash metal' ),
    (10, 'death metal', 4, 8, 'thrash metal' ),
    (11, 'doom metal', 4 ),
    (12, 'drone metal', 4, 11, 'doom metal' ),
    (13, 'sludge metal', 4, 11, 'doom metal' ),
    (14, 'groove metal', 4, 8, 'thrash metal' ),
    (15, 'southern metal', 2, 'country', 4, ),
    (16, 'nu metal', 10, 'rap', 4 ),
    (17, 'industrial metal', 11, 'edm', 4 ),
    (18, 'funk metal', 7, 'funk', 4 ),
    (19, 'stoner metal', 4 ),
    (20, 'blues rock', 6, 3, 'blues' ),
    (21, 'rockabilly', 6 ),
    (22, 'southern rock', 6, 2, 'country' ),
    (23, 'psychadelic rock', 6 ),
    (24, 'hard rock', 6 ),
    (25, 'punk rock', 6, 8, 'punk' ),
    (26, 'alt rock', 6 ),
    (27, 'pop rock', 6, 9, 'pop' ),
    (28, 'symphonic rock', 6, 1, 'classical' ),
    (29, 'stoner rock', 6 ),
    (30, 'funk rock', 6, 7, 'funk' ),
    (31, 'afro punk', 8 ),
    (32, 'anarcho punk', 8 ),
    (33, 'art punk', 8 ),
    (34, 'crust punk', 8 ),
    (35, 'egg punk', 8 ),
    (36, 'glitter punk', 8, 4, 'hair metal' ),
    (37, 'hardcore punk', 8, 4, 'metal' ),
    (38, 'thrash punk', 8, 8, 'thrash metal' ),
    (39, 'horror punk', 8 ),
    (40, 'pop punk', 8, 9, 'pop' ),
    (41, 'skate punk', 8, 40, 'pop punk' ),
    (42, 'trallpunk', 8 ),
    (43, 'deep funk', 7 ),
    (44, 'go-go funk', 7 ),
    (45, 'afrobeat funk', 7 ),
    (46, 'boogie funk', 7 ),
    (47, 'delta blues', 3, 2, 'country' ),
    (48, 'chicago blues', 3 ),
    (49, 'boogie woogie blues', 3 ),
    (50, 'memphis blues', 3 ),
    (51, 'jump blues', 3 ),
    (52, 'west coast blues', 3, 2, 'country' ),
    (53, 'new orleans blues', 3 ),
    (54, 'texas blues', 3, 2, 'country' ),
    (55, 'classic country', 2 ),
    (56, 'western country', 2 ),
    (57, 'honky tonk', 2 ),
    (58, 'outlaw country', 2 ),
    (59, 'prog country', 2, 5, 'jazz' ),
    (60, 'truck country', 2 ),
    (61, 'bro country', 2 ),
    (62, 'neotraditional country', 2 ),
    (63, 'baroque', 1 ),
    (64, 'opera',  1),
    (65, 'old school rap', 10 ),
    (66, 'golden age rap', 10 ),
    (67, 'gangster rap', 10 ),
    (68, 'country rap', 2, 'country', 10 ),
    (69, 'boom bap', 10 ),
    (70, 'conscious hip-hop', 10 ),
    (71, 'trap', 10 ),
    (72, 'jazz rap', 10, 5, 'jazz' ),
    (73, 'afro pop', 9 ),
    (74, 'baroque pop', 9 ),
    (75, 'country pop', 9 ),
    (76, 'electro pop', 9 ),
    (77, 'prog pop', 9 ),
    (78, 'acid jazz', 5 ),
    (79, 'bebop jazz', 5 ),
    (80, 'cool jazz', 5 ),
    (81, 'big band', 5 ),
    (82, 'chamber jazz', 5 ),
    (83, 'crossover jazz', 5 ),
    (84, 'ethio jazz', 5 ),
    (85, 'nu jazz', 5 ),
    (86, 'orchestral jazz', 5, 1, 'classical' ),
    (87, 'punk jazz', 5, 8, 'punk' ),
    (88, 'third-stream jazz', 5 ),
    (89, 'house', 11 ),
    (90, 'dubstep', 11 ),
    (91, 'trance', 11 )