/**
 * @param { import("knex").knex } knex
 * @returns { promise<void> } 
 */
exports.seed = async function(knex) {
  // deletes all existing entries
  await knex('subgenres').del()
  await knex('subgenres').insert([
    {id: 1, subgenre_name: 'speed metal', origin_id: 4, inspiration_id: 1, inspiration_name: 'classical' },
    {id: 2, subgenre_name: 'power metal', origin_id: 4, inspiration_id: 1, inspiration_name: 'classical', derivative_id: 1, derivative_name: 'speed metal' },
    {id: 3, subgenre_name: 'pop metal', inspiration_id: 9, inspiration_name: 'pop', origin_id: 4 },
    {id: 4, subgenre_name: 'hair metal', inspiration_id: 1, inspiration_name: 'rock', origin_id: 4 },
    {id: 5, subgenre_name: 'neoclassical metal', origin_id: 4, inspiration_id: 1, inspiration_name: 'classical' },
    {id: 6, subgenre_name: 'symphonic metal', origin_id: 4, inspiration_id: 1, inspiration_name: 'classical' },
    {id: 7, subgenre_name: 'prog metal', inspiration_id: 1, inspiration_name: 'jazz', origin_id: 4 },
    {id: 8, subgenre_name: 'thrash metal', inspiration_id: 1, inspiration_name: 'punk', origin_id: 4 },
    {id: 9, subgenre_name: 'black metal', origin_id: 4, derivative_id: 8, derivative_name: 'thrash metal' },
    {id: 10, subgenre_name: 'death metal', origin_id: 4, derivative_id: 8, derivative_name: 'thrash metal' },
    {id: 11, subgenre_name: 'doom metal', origin_id: 4 },
    {id: 12, subgenre_name: 'drone metal', origin_id: 4, derivative_id: 11, derivative_name: 'doom metal' },
    {id: 13, subgenre_name: 'sludge metal', origin_id: 4, derivative_id: 11, derivative_name: 'doom metal' },
    {id: 14, subgenre_name: 'groove metal', origin_id: 4, derivative_id: 8, derivative_name: 'thrash metal' },
    {id: 15, subgenre_name: 'southern metal', inspiration_id: 2, inspiration_name: 'country', origin_id: 4, },
    {id: 16, subgenre_name: 'nu metal', inspiration_id: 1, inspiration_name: 'rap', origin_id: 4 },
    {id: 17, subgenre_name: 'industrial metal', inspiration_id: 1, inspiration_name: 'edm', origin_id: 4 },
    {id: 18, subgenre_name: 'funk metal', inspiration_id: 7, origin_id: 4 },
    {id: 19, subgenre_name: 'stoner metal', origin_id: 4 },
    {id: 20, subgenre_name: 'blues rock', origin_id: 6, inspiration_id: 3, inspiration_name: 'blues' },
    {id: 21, subgenre_name: 'rockabilly', origin_id: 6 },
    {id: 22, subgenre_name: 'southern rock', origin_id: 6, inspiration_id: 2, inspiration_name: 'country' },
    {id: 23, subgenre_name: 'psychadelic rock', origin_id: 6 },
    {id: 24, subgenre_name: 'hard rock', origin_id: 6 },
    {id: 25, subgenre_name: 'punk rock', origin_id: 6, inspiration_id: 8, inspiration_name: 'punk' },
    {id: 26, subgenre_name: 'alt rock', origin_id: 6 },
    {id: 27, subgenre_name: 'pop rock', origin_id: 6, inspiration_id: 9, inspiration_name: 'pop' },
    {id: 28, subgenre_name: 'symphonic rock', origin_id: 6, inspiration_id: 1, inspiration_name: 'classical' },
    {id: 29, subgenre_name: 'stoner rock', origin_id: 6 },
    {id: 30, subgenre_name: 'funk rock', origin_id: 6, inspiration_id: 7, inspiration_name: 'funk' },
    {id: 31, subgenre_name: 'afro punk', origin_id: 8 },
    {id: 32, subgenre_name: 'anarcho punk', origin_id: 8 },
    {id: 33, subgenre_name: 'art punk', origin_id: 8 },
    {id: 34, subgenre_name: 'crust punk', origin_id: 8 },
    {id: 35, subgenre_name: 'egg punk', origin_id: 8 },
    {id: 36, subgenre_name: 'glitter punk', origin_id: 8, derivative_id: 4, derivative_name: 'hair metal' },
    {id: 37, subgenre_name: 'hardcore punk', origin_id: 8, inspiration_id: 4, inspiration_name: 'metal' },
    {id: 38, subgenre_name: 'thrash punk', origin_id: 8, derivative_id: 8, derivative_name: 'thrash metal' },
    {id: 39, subgenre_name: 'horror punk', origin_id: 8 },
    {id: 40, subgenre_name: 'pop punk', origin_id: 8, inspiration_id: 9, inspiration_name: 'pop' },
    {id: 41, subgenre_name: 'skate punk', origin_id: 8, derivative_id: 40, derivative_name: 'pop punk' },
    {id: 42, subgenre_name: 'trallpunk', origin_id: 8 },
    {id: 43, subgenre_name: 'deep funk', origin_id: 7 },
    {id: 44, subgenre_name: 'go-go funk', origin_id: 7 },
    {id: 45, subgenre_name: 'afrobeat funk', origin_id: 7 },
    {id: 46, subgenre_name: 'boogie funk', origin_id: 7 },
    {id: 47, subgenre_name: 'delta blues', origin_id: 3, inspiration_id: 2, inspiration_name: 'country' },
    {id: 48, subgenre_name: 'chicago blues', origin_id: 3 },
    {id: 49, subgenre_name: 'boogie woogie blues', origin_id: 3 },
    {id: 50, subgenre_name: 'memphis blues', origin_id: 3 },
    {id: 51, subgenre_name: 'jump blues', origin_id: 3 },
    {id: 52, subgenre_name: 'west coast blues', origin_id: 3, inspiration_id: 2, inspiration_name: 'country' },
    {id: 53, subgenre_name: 'new orleans blues', origin_id: 3 },
    {id: 54, subgenre_name: 'texas blues', origin_id: 3, inspiration_id: 2, inspiration_name: 'country' },
    {id: 55, subgenre_name: 'classic country', origin_id: 2 },
    {id: 56, subgenre_name: 'western country', origin_id: 2 },
    {id: 57, subgenre_name: 'honky tonk', origin_id: 2 },
    {id: 58, subgenre_name: 'outlaw country', origin_id: 2 },
    {id: 59, subgenre_name: 'prog country', origin_id: 2, inspiration_id: 5, inspiration_name: 'jazz' },
    {id: 60, subgenre_name: 'truck country', origin_id: 2 },
    {id: 61, subgenre_name: 'bro country', origin_id: 2 },
    {id: 62, subgenre_name: 'neotraditional country', origin_id: 2 },
    {id: 63, subgenre_name: 'baroque', origin_id: 1 },
    {id: 64, subgenre_name: 'opera',  origin_id: 1},
    {id: 65, subgenre_name: 'old school rap', origin_id: 10 },
    {id: 66, subgenre_name: 'golden age rap', origin_id: 10 },
    {id: 67, subgenre_name: 'gangster rap', origin_id: 10 },
    {id: 68, subgenre_name: 'country rap', inspiration_id: 2, inspiration_name: 'country', origin_id: 10 },
    {id: 69, subgenre_name: 'boom bap', origin_id: 10 },
    {id: 70, subgenre_name: 'conscious hip-hop', origin_id: 10 },
    {id: 71, subgenre_name: 'trap', origin_id: 10 },
    {id: 72, subgenre_name: 'jazz rap', origin_id: 10, inspiration_id: 5, inspiration_name: 'jazz' },
    {id: 73, subgenre_name: 'afro pop', origin_id: 9 },
    {id: 74, subgenre_name: 'baroque pop', origin_id: 9 },
    {id: 75, subgenre_name: 'country pop', origin_id: 9 },
    {id: 76, subgenre_name: 'electro pop', origin_id: 9 },
    {id: 77, subgenre_name: 'prog pop', origin_id: 9 },
    {id: 78, subgenre_name: 'acid jazz', origin_id: 5 },
    {id: 79, subgenre_name: 'bebop jazz', origin_id: 5 },
    {id: 80, subgenre_name: 'cool jazz', origin_id: 5 },
    {id: 81, subgenre_name: 'big band', origin_id: 5 },
    {id: 82, subgenre_name: 'chamber jazz', origin_id: 5 },
    {id: 83, subgenre_name: 'crossover jazz', origin_id: 5 },
    {id: 84, subgenre_name: 'ethio jazz', origin_id: 5 },
    {id: 85, subgenre_name: 'nu jazz', origin_id: 5 },
    {id: 86, subgenre_name: 'orchestral jazz', origin_id: 5, inspiration_id: 1, inspiration_name: 'classical' },
    {id: 87, subgenre_name: 'punk jazz', origin_id: 5, inspiration_id: 8, inspiration_name: 'punk' },
    {id: 88, subgenre_name: 'third-stream jazz', origin_id: 5 },
    {id: 89, subgenre_name: 'house', origin_id: 11 },
    {id: 90, subgenre_name: 'dubstep', origin_id: 11 },
    {id: 91, subgenre_name: 'trance', origin_id: 11 },
  ])
};
