/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('subgenres').del()
  await knex('subgenres').insert([
    {id: 1, subgenre_name: 'Speed Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 2, subgenre_name: 'Power Metal', origin_name: 'Metal', origin_id: 4, derivative_name: 'Speed Metal', derivative_id: 1 },
    {id: 3, subgenre_name: 'Pop Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 4, subgenre_name: 'Hair Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 5, subgenre_name: 'Neoclassical Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 6, subgenre_name: 'Symphonic Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 7, subgenre_name: 'Prog Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 8, subgenre_name: 'Thrash Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 9, subgenre_name: 'Black Metal', origin_name: 'Metal', origin_id: 4, derivative_name: 'Thrash Metal', derivative_id: 8 },
    {id: 10, subgenre_name: 'Death Metal', origin_name: 'Metal', origin_id: 4, derivative_name: 'Thrash Metal', derivative_id: 8 },
    {id: 11, subgenre_name: 'Doom Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 12, subgenre_name: 'Drone Metal', origin_name: 'Metal', origin_id: 4, derivative_name: 'Doom Metal', derivative_id: 11 },
    {id: 13, subgenre_name: 'Sludge Metal', origin_name: 'Metal', origin_id: 4, derivative_name: 'Doom Metal', derivative_id: 11 },
    {id: 14, subgenre_name: 'Groove Metal', origin_name: 'Metal', origin_id: 4, derivative_name: 'Thrash Metal', derivative_id: 8 },
    {id: 15, subgenre_name: 'Southern Metal', origin_name: 'Metal', origin_id: 4, },
    {id: 16, subgenre_name: 'Nu Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 17, subgenre_name: 'Industrial Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 18, subgenre_name: 'Funk Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 19, subgenre_name: 'Southern Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 20, subgenre_name: 'Stoner Metal', origin_name: 'Metal', origin_id: 4 },
    {id: 21, subgenre_name: 'Blues Rock', origin_name: 'Rock', origin_id: 6 },
    {id: 22, subgenre_name: 'Blues Rock', origin_name: 'Rock', origin_id: 6 },
    {id: 23, subgenre_name: 'Rockabilly', origin_name: 'Rock', origin_id: 6 },
    {id: 24, subgenre_name: 'Southern Rock', origin_name: 'Rock', origin_id: 6 },
    {id: 25, subgenre_name: 'Psychadelic Rock', origin_name: 'Rock', origin_id: 6 },
    {id: 26, subgenre_name: 'Hard Rock', origin_name: 'Rock', origin_id: 6 },
    {id: 27, subgenre_name: 'Punk Rock', origin_name: 'Rock', origin_id: 6 },
    {id: 28, subgenre_name: 'Alt Rock', origin_name: 'Rock', origin_id: 6 },
    {id: 29, subgenre_name: 'Pop Rock', origin_name: 'Rock', origin_id: 6 },
    {id: 30, subgenre_name: 'Symphonic Rock', origin_name: 'Rock', origin_id: 6 },
    {id: 31, subgenre_name: 'Stoner Rock', origin_name: 'Rock', origin_id: 6 },
    {id: 32, subgenre_name: 'Funk Rock', origin_name: 'Rock', origin_id: 6 },
    {id: 33, subgenre_name: 'Afro Punk', origin_name: 'Punk', origin_id: 8 },
    {id: 34, subgenre_name: 'Anarcho Punk', origin_name: 'Punk', origin_id: 8 },
    {id: 35, subgenre_name: 'Art Punk', origin_name: 'Punk', origin_id: 8 },
    {id: 36, subgenre_name: 'Crust Punk', origin_name: 'Punk', origin_id: 8 },
    {id: 37, subgenre_name: 'Egg Punk', origin_name: 'Punk', origin_id: 8 },
    {id: 38, subgenre_name: 'Glitter Punk', origin_name: 'Punk', origin_id: 8 },
    {id: 39, subgenre_name: 'Hardcore Punk', origin_name: 'Punk', origin_id: 8 },
    {id: 40, subgenre_name: 'Thrash Punk', origin_name: 'Punk', origin_id: 8, derivative_name: 'Thrash Metal', derivative_id: 8 },
    {id: 41, subgenre_name: 'Horror Punk', origin_name: 'Punk', origin_id: 8 },
    {id: 42, subgenre_name: 'Pop Punk', origin_name: 'Punk', origin_id: 8 },
    {id: 43, subgenre_name: 'Skate Punk', origin_name: 'Punk', origin_id: 8, derivative_name: 'Pop Punk', derivative_id: 42 },
    {id: 44, subgenre_name: 'TrallPunk', origin_name: 'Punk', origin_id: 8 },
    {id: 45, subgenre_name: 'Deep Funk', origin_name: 'Funk', origin_id: 7 },
    {id: 46, subgenre_name: 'Go-go', origin_name: 'Funk', origin_id: 7 },
    {id: 47, subgenre_name: 'Afrobeat', origin_name: 'Funk', origin_id: 7 },
    {id: 48, subgenre_name: 'Boogie', origin_name: 'Funk', origin_id: 7 },
    {id: 49, subgenre_name: 'Delta Blues', origin_name: 'Blues', origin_id: 3 },
    {id: 50, subgenre_name: 'Chicago Blues', origin_name: 'Blues', origin_id: 3 },
    {id: 51, subgenre_name: 'Boogie Woogie', origin_name: 'Blues', origin_id: 3 },
    {id: 52, subgenre_name: 'Memphix Blues', origin_name: 'Blues', origin_id: 3 },
    {id: 53, subgenre_name: 'Jump Blues', origin_name: 'Blues', origin_id: 3 },
    {id: 54, subgenre_name: 'West Coast Blues', origin_name: 'Blues', origin_id: 3 },
    {id: 55, subgenre_name: 'New Orleans Blues', origin_name: 'Blues', origin_id: 3 },
    {id: 56, subgenre_name: 'Texas Blues', origin_name: 'Blues', origin_id: 3 },
    {id: 57, subgenre_name: 'Classic Country', origin_name: 'Country', origin_id: 2 },
    {id: 58, subgenre_name: 'Western Country', origin_name: 'Country', origin_id: 2 },
    {id: 59, subgenre_name: 'Honky Tonk', origin_name: 'Country', origin_id: 2 },
    {id: 60, subgenre_name: 'Outlaw Country', origin_name: 'Country', origin_id: 2 },
    {id: 61, subgenre_name: 'Prog Country', origin_name: 'Country', origin_id: 2 },
    {id: 62, subgenre_name: 'Truck Country', origin_name: 'Country', origin_id: 2 },
    {id: 63, subgenre_name: 'Bro Country', origin_name: 'Country', origin_id: 2 },
    {id: 64, subgenre_name: 'Neotraditional Country', origin_name: 'Country', origin_id: 2 },
    {id: 65, subgenre_name: 'Baroque', origin_name: 'Classical Music', origin_id: 1 },
    {id: 66, subgenre_name: 'Opera',  origin_name: 'Classical Music', origin_id: 1},
    {id: 67, subgenre_name: 'Old School Rap', origin_name: 'Rap', origin_id: 10 },
    {id: 68, subgenre_name: 'Golden Age Rap', origin_name: 'Rap', origin_id: 10 },
    {id: 69, subgenre_name: 'Gangster Rap', origin_name: 'Rap', origin_id: 10 },
    {id: 70, subgenre_name: 'Country Rap', origin_name: 'Rap', origin_id: 10 },
    {id: 71, subgenre_name: 'Boom Bap', origin_name: 'Rap', origin_id: 10 },
    {id: 72, subgenre_name: 'Conscious Hip-Hop', origin_name: 'Rap', origin_id: 10 },
    {id: 73, subgenre_name: 'Trap', origin_name: 'Rap', origin_id: 10 },
    {id: 74, subgenre_name: 'Jazz Rap', origin_name: 'Rap', origin_id: 10 },
    {id: 75, subgenre_name: 'Afro Pop', origin_name: 'Pop', origin_id: 9 },
    {id: 76, subgenre_name: 'Baroque Pop', origin_name: 'Pop', origin_id: 9 },
    {id: 77, subgenre_name: 'Country Pop', origin_name: 'Pop', origin_id: 9 },
    {id: 78, subgenre_name: 'Electro Pop', origin_name: 'Pop', origin_id: 9 },
    {id: 79, subgenre_name: 'Prog Pop', origin_name: 'Pop', origin_id: 9 },
    {id: 80, subgenre_name: 'Acid Jazz', origin_name: 'Jazz', origin_id: 5 },
    {id: 81, subgenre_name: 'Bebop Jazz', origin_name: 'Jazz', origin_id: 5 },
    {id: 82, subgenre_name: 'Cool Jazz', origin_name: 'Jazz', origin_id: 5 },
    {id: 83, subgenre_name: 'Big Band', origin_name: 'Jazz', origin_id: 5 },
    {id: 84, subgenre_name: 'Chamber Jazz', origin_name: 'Jazz', origin_id: 5 },
    {id: 85, subgenre_name: 'Crossover Jazz', origin_name: 'Jazz', origin_id: 5 },
    {id: 86, subgenre_name: 'Ethio Jazz', origin_name: 'Jazz', origin_id: 5 },
    {id: 87, subgenre_name: 'Nu Jazz', origin_name: 'Jazz', origin_id: 5 },
    {id: 88, subgenre_name: 'Orchestral Jazz', origin_name: 'Jazz', origin_id: 5 },
    {id: 89, subgenre_name: 'Punk Jazz', origin_name: 'Jazz', origin_id: 5 },
    {id: 90, subgenre_name: 'Third-stream Jazz', origin_name: 'Jazz', origin_id: 5 },
    {id: 91, subgenre_name: 'House', origin_name: 'EDM', origin_id: 11 },
    {id: 92, subgenre_name: 'Dubstep', origin_name: 'EDM', origin_id: 11 },
    {id: 93, subgenre_name: 'Trance', origin_name: 'EDM', origin_id: 11 },
  ]);
};
